bind 127.0.0.1
protected-mode yes
port 6380
timeout 0
tcp-keepalive 300
daemonize no
supervised no
databases 1
save ""
appendonly no
maxmemory 48mb
maxmemory-policy allkeys-lru
loglevel notice
dir /var/lib/borotalk/redis
